version: '3.7'
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        tty: true
        ports:
            - '3000:3000'
        volumes:
            - ./client:/app
            - /app/node_modules
